### ISSUE TITLE
LMCC EV Telemetry - Biomedical and Space Suit Data Tables - Primary

### ISSUE THREAD

**Issue by ainsley37** [BSU-SUITS-Team/ARSIS#160]
Reference #137 

Given: Biomedical and space suit data from TSS 
When: IVA navigates to "Biometrics and Spacesuit Data" page in LMCC 
Then: Displays biomedical and space suit data table in LMCC (reference Figure 4, pg. 9 of proposal)

**Comment by dignojrteogalbo** [comment]
![image](https://github.com/BSU-SUITS-Team/ARSIS/assets/49927429/1f55a5c4-0765-4bae-aef1-c8c3b39e10b3)
